image: node:latest

stages:
    - setup
    - test
    - deploy
    - deploy-qa
    - deploy-v4
    - i18n-upgrade-app
    - i18n-to-crowdin

variables:
    NODE_OPTIONS: --max-old-space-size=4096

before_script:
 - apt-get -y update
 - 'which ssh-agent || apt-get -y install openssh-client'
 - eval $(ssh-agent -s)
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
 - git config --global user.email $GIT_CI_EMAIL
 - git config --global user.name $GIT_CI_USERNAME
 - mkdir ~/.ssh 2> /dev/null
 - ssh-keyscan -t rsa ${CI_SERVER_HOST} > ~/.ssh/known_hosts
 - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
 - git remote -v
 - git clone "$CI_SCRIPTS_GIT" --depth 1 ci-scripts
 - ls -l

setup:
    stage: setup
    script:
        - ./ci-scripts/prepare-ci.sh install-app --remote "$APP_GIT"
    artifacts:
        expire_in: 1 days
        paths:
            - node_modules/
            - src/app/config.js
            - env/.env
            - .gitconfig
            - env/env.json

lint:
    stage: test
    script:
        - npm run lint
        - ./tasks/checkInjector.sh --lint

i18n:
    stage: test
    script:
        - npm run i18n:extract
        - npm run i18n:check -- --debug

i18n-upgrade-app:
    stage: i18n-upgrade-app
    tags:
        - heavy
    script:
        - ./ci-scripts/prepare-ci.sh i18n upgrade-app --limit "$I18N_APPROVED"
    when: manual

i18n-to-crowdin:
    stage: i18n-to-crowdin
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh i18n to-crowdin
    when: manual

deploy:
    stage: deploy
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh install-app-remote
        - ./ci-scripts/prepare-ci.sh deploy-app --branch "$BRANCH_DEPLOY" --api "$API_DEPLOY"
    when: manual

deploy-qa:
    stage: deploy-qa
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh install-app-remote --update-lock
        - ./ci-scripts/prepare-ci.sh deploy-app --branch "$BRANCH_DEPLOY_QA" --api "$API_DEPLOY"
    when: manual

deploy-v4:
    stage: deploy-v4
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh install-app-remote --angular-v4
        - ./ci-scripts/prepare-ci.sh deploy-app --branch "$BRANCH_DEPLOY_QA" --api "$API_DEPLOY"
    when: manual
